// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Wallet struct {
	Address string `json:"address"`
	Tokens  string `json:"tokens"`
}
